[package]
name = "mogwai"
version = "0.0.0"
authors = ["Schell Scivally <efsubenovex@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The magical, obvious, graphical, web application interface."
readme = "README.md"
keywords = ["ui", "dom", "app", "frp"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
console_log = "0.1.2"
log = "0.4"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.31"
features = [
  "CharacterData",
  "CssStyleDeclaration",
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "Node",
  "Text",
  "Window"
]
