[package]
name = "mogwai"
version = "0.0.0"
authors = ["Schell Scivally <efsubenovex@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The magical, obvious, graphical, web application interface."
readme = "../README.md"
keywords = ["ui", "dom", "app", "frp", "reactive"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
console_log = "0.1.2"
futures = "0.3"
js-sys = "0.3.27"
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3.31"
features = [
  "CharacterData",
  "CssStyleDeclaration",
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Node",
  "Text",
  "Window",
  "XmlHttpRequest"
]