name: build, test, doc, publish to crates.io

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: icepuma/rust-action@master
      with:
        args: |
          cargo build
          cargo test
          cargo doc
          cargo publish --token ${{ secrets.cargo_token }}
