name: build, test, doc

on:
  push:
    branches-ignore:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: icepuma/rust-action@master
      with:
        args: |
          cargo build \
          && cargo test \
          && cargo doc \
          && cd mogwai \
          && cargo publish --dry-run
