name: build, test, doc

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: icepuma/rust-action@master
      with:
        args: |
          cargo build
          cargo test
          cargo doc
          cargo publish --dry-run
